### ISSUE TITLE
Error installing in Laravel 10

### ISSUE THREAD

**Issue by malf88** [spatie/laravel-route-attributes#116]
Goodnight.
I'm having a problem installing the library in Laravel 10, after the installation is complete I'm getting the error "Unable to detect application namespace.".
The same stops happening after removing the library.

**Comment by Tjoosten** [comment]
Have u changed the default application namespace?

**Comment by malf88** [comment]
Yes, I changed psr4 in composer.json to "App\\": "app/System/",

**Comment by Tjoosten** [comment]
But the problem keeps occuring after removing the package? If yes. I think the problem is withing not project. and not the package.

**Comment by malf88** [comment]
The problem no longer occurs when removing the package.

**Comment by Tjoosten** [comment]
And what if you just copy manually the config file into the project. and run `composer dump-autoload`?

**Comment by malf88** [comment]
The error happens when the directory is placed in the configuration file. If it is omitted, the error does not occur.
```
'directories' => [
        //app_path('Http/Controllers'),
        /*
        app_path('Http/Controllers/Api') => [
           'prefix' => 'api',
           'middleware' => 'api',
        ],
        */
    ],
```

**Comment by Tjoosten** [comment]
When u changed ur psr namespace en break lose from the default structure. Did you also changed your base path for the application. in `Application.php`

**Comment by malf88** [comment]
I managed to solve it by fixing the namespace in psr4 and changing the namespace of the classes and their references.

Thank you for your help.
