### ISSUE TITLE
Unit testing failed

### ISSUE THREAD

**Issue by qindj** [spatie/laravel-route-attributes#18]
this line:

https://github.com/spatie/laravel-route-attributes/blob/6fb6756b0fcfff0edd7023a950345841c7a67df6/src/RouteAttributesServiceProvider.php#L37

with app()->runningUnitTests() ? $testClassDirectory  will cause normal unit tests failed

errors:

![image](https://user-images.githubusercontent.com/1707762/104307713-8a1b2200-550a-11eb-8699-b1ba2d351b05.png)

**Comment by freekmurze** [comment]
Feel free to submit a PR that fixes this problem for you.
