### ISSUE TITLE
[Discussion] Code Restructure

### ISSUE THREAD

**Issue by christian98** [spatie/laravel-route-attributes#3]
Hey,
first, thanks for creating this package! I think this could be a really handy package for developing with PHP 8 and Laravel!

But I have a few concerns about the Code structure. I would like to hear your thoughts about that.
Mainly, what was the intention to put all logic inside the ```RouteRegistrar.php``` and not inside the Attributes itself?
In my opinion, seperating the code, would give the package the ability to receive and maintain new features in an easier way.

My preference would be, that there are Interfaces for Class and Method Attributes, that force you to implement a given method like this:
```php
interface RouteMethod {
    public function executeMethodAttribute(ReflectionClass $class, ReflectionMethod $method, ?Illuminate\Routing\Route $route);
}

interface RouteClass {
    public function executeClassAttribute(ReflectionClass $class, ?Illuminate\Routing\Route $route);
}
```
All Attribute related (and most likely very specific) Code would go inside these Methods inside their Attribute-Class.
An Sample Attribute could look something like this:
```php
#[Attribute(Attribute::TARGET_CLASS)]
class Middleware implements RouteClass
{
    public array $middleware = [];

    public function __construct(string|array $middleware = [])
    {
        $this->middleware = Arr::wrap($middleware);
    }

    public function executeClassAttribute(ReflectionClass $class, ?Illuminate\Routing\Route $route) {
        // do some middleware stuff here
    }
}
```
This way the ```RouteRegistrar.php``` would not get cluttered and hard to maintain. A problem with this is the start, the way a new Route will be instantiated. (I do not know if the Attributes are always in the same order, as they appear in the Controller-Classes...)

I know this is not a finished concept and there has to be some more thinking to be done.
Now I want to know your opinions ;)

**Comment by freekmurze** [comment]
> Mainly, what was the intention to put all logic inside the RouteRegistrar.php and not inside the Attributes itself?

We have considered this, but left it in the registrar because we can image that we'll have more than one method attribute influencing a route. Image `RouteName` and `Middleware` annotations on a certain controller method. It's easier to combine those effects in the registrar.

I think the registrar complexity is not too bad at the moment. We will refactor some parts should it get unwieldy. But for now, it's nice and simple.

**Comment by freekmurze** [comment]
Thanks for your efforts writing your thoughts down!
