### ISSUE TITLE
Middleware inheritance

### ISSUE THREAD

**Issue by Radiergummi** [spatie/laravel-route-attributes#30]
Now that I've converted our entire API to use route attributes, I've noticed some patterns that I would like to improve. In particular, it's a little cumbersome that overriding middleware set on the controller level is impossible:

```php
use Spatie\RouteAttributes\Attributes as Routing;

#[Routing\Middleware('throttle:200')] 
class FooController
{
    #[Routing\Middleware('throttle:2')]      <-- will add another throttle middleware
    public function expensiveCall(): Response;
}
```

While this makes perfect sense, it requires me to define the middleware on every method explicitly, only because I have single culprit with different requirements. I've been thinking about how to solve this, and would like to suggest adding a `WithoutMiddleware` attribute:

```php
use Spatie\RouteAttributes\Attributes as Routing;

#[Routing\Middleware('throttle:200')] 
class FooController
{
    #[Routing\WithoutMiddleware('throttle:200')]  <-- removes the middleware inherited from the controller
    #[Routing\Middleware('throttle:2')]
    public function expensiveCall(): Response;
}
```

This isn't really elegant, though. Would anyone have a better idea?

**Comment by freekmurze** [comment]
Feel free to PR this included tests and an updated readme. Thanks!

**Comment by lloricode** [comment]
my solution is just adding middleware on specific endpoint by overide it

```php

#[Middleware(['api'])]
#[Prefix('api')]
#[Resource('quotes', apiResource: true)]
class QuoteController extends Controller
{
    // ...

    #[Post(uri: 'quotes', name: 'quotes.store', middleware: 'auth')]
    public function store(CreateQuoteFormRequest $request): JsonResponse
    {
        // ...
    }

    // ...
```
