### ISSUE TITLE
Cannot declare class because the name is already in use

### ISSUE THREAD

**Issue by tekord** [spatie/laravel-route-attributes#57]
I have multiple directories with the Controller base class like that:

- App\Modules\Admin
- - Controller
- - DashboardController
- App\Modules\Api
- - Controller
- - UserController

When I specified all these directories in the 'directories' parameter (route-attributes.php file) I got the following error:

```
Cannot declare class App\Modules\Api\Controllers\Controller, because the name is already in use
```

So, it is impossible to use this package when an application has controller classes with the same name.

PHP 8.0.11
Laravel 8.64

**Comment by sebapastore** [comment]
Trying to solve this issue I came up with the conclusion that there is not an error.

As the package has no tests, I created a [project](https://github.com/sebapastore/test-laravel-routes-attributes) in order show that.

I was able to reproduce the error when the Controllers have the same name and the same namespace. Anyway, this is expected and not an issue itself.

**Comment by Tofandel** [comment]
Yes it just means you messed up the namespace, you just copied App\Modules\Api\Controller\Controller.php to App\Modules\Admin\Controller\Controller.php without changing the namespace

If you look in `App\Modules\Admin\Controller\Controller.php`

You'll see `namespace App\Modules\Api\Controller`
