### ISSUE TITLE
Middleware usage, with Laravel 8

### ISSUE THREAD

**Issue by TheMrViper** [spatie/laravel-route-attributes#66]
Is the middleware section in config is full replacement of Kernel.php array? 

I tried to move middlewares from Kernel.php to config file, and found a bug, for me it was a cors issue - i mean this middleware was not worked at all. 
So in situation when i moved Cors middleware to config - its not working
Leave it in Kernel - working

For my own middleware, it works well in both places but also if i leave it in Kernel & config, it will be called twice

// UDPATE 
Also SubstituteBindings, is not working if i put it in Kernel, and start work if i put it to config, can anyone explain why? 

If its not a full replacement, then why we need it in config section? 

my versions: 
`"laravel/framework": "^8.12"`
`"spatie/laravel-route-attributes": "^1.9"`

**Comment by freekmurze** [comment]
According to our tests it should work.

Please PR a test that demonstrates to problem (and optionally a fix that fixes this if a problem is found).
