### ISSUE TITLE
[Feature Request] Add to a Blade or Livewire view component to create a route directly from the component

### ISSUE THREAD

**Issue by patrickcurl** [spatie/laravel-route-attributes#75]
I think it'd be cool if you could add a route to a file in View/Components/SomeBladeComponent.php

That would essentially return View::make($view, $data) where data is some defaults or mock data passed to preview the component.

**Comment by patrickcurl** [comment]
Nevermind, I'm an idiot.... 

just adding the view folder to the config, and then adding this: 

```
#[Get('blade-test')]
    public function get()
    {
        return $this->render();
    }

```
Got me there. 

Would be cool to add that to the docs in case others want a similar thing done...

**Comment by freekmurze** [comment]
Nice that you found a solution 👍 

Feel free to send a PR to that docs.

**Comment by juliomotol** [comment]
For Livewire, you'll need do:
```php
#[Get('password/reset', 'password.request')]
public function __invoke(Container $container, Route $route){
    return parent::__invoke($container, $route);
}
```
Although this feels a bit extraneous.

**Comment by juliomotol** [comment]
@freekmurze would you be open to the idea of having a Livewire route attribute that can be applied to a Livewire component class?

**Comment by freekmurze** [comment]
No, I think I don't want to have anything specific to Livewire in this package for now.

**Comment by juliomotol** [comment]
what about allowing `Route` to be attributed to classes and when done so, it will just register to `__invoke`. As of the moment, it can only be attributed to methods.

**Comment by juliomotol** [comment]
I've dug through the package this weekend and found that it would need much work for it to work. We'll just proceed the workaround but I'd definitely love to see this in the future.
