### ISSUE TITLE
Route model binding doesn't work with Resource attribute

### ISSUE THREAD

**Issue by samyrataylor** [spatie/laravel-route-attributes#76]
When using the `Resource` attribute, implicit route model binding does not work. 

For example:

```php
namespace App\Http\Controllers;

use App\Models\User;
use Spatie\RouteAttributes\Attributes\Resource;

#[Resource('user')]
class UserController extends Controller
{
    public function show(User $user)
    {
        dd($user);
    }
}

```

When visiting `/user/1` the expected result would be an instance of the `User` model with id of 1.

The actual result is an empty instance of the `User` model. (Same as returning `new User()`

---

If the model's type hint is removed we just get the passed `id`

```php
public function show($user)
{
    dd($user);
}
```

Visiting `/user/1` simply returns `"1"`

--- 

The desired result can be achieved using the `Get` attribute:

```php
#[Get('/user/{user}')]
public function show(User $user)
{
    dd($user);
}
```

Visiting `/user/1` correctly returns an instance of the `User` model with id of 1

This works both with and without including the `Resource` attribute in the controller.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.
