### ISSUE TITLE
Feature: Domain attribute

### ISSUE THREAD

**Issue by robertdrakedennis** [spatie/laravel-route-attributes#9]
Hi there, I was wondering what your thoughts on adding ``domain`` as one of the argument / features for routing? I'm currently looking into using this for a tenancy based project and was wondering on what your thoughts would be for it. Thanks!

**Comment by freekmurze** [comment]
If the code is simple, I'd accept a PR for this with updated tests/readme.

**Comment by robertdrakedennis** [comment]
I have never written a test before but I'll try my best
